---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-benchmarker
  name: kafka-benchmarker
  namespace: sre-test-kafka
spec:
  containers:
  - env:
    - name: BOOTSTRAP_SERVERS
      value: sre-test-kafka-bootstrap.sre-test-kafka.svc:9092
    - name: HOME
      value: /tmp
    image: quay.io/fciocchetti0/kafka-benchmarker:master
    imagePullPolicy: Always
    name: kafka-benchmarker
    resources:
      limits:
        cpu: "2"
        memory: 3Gi
      requests:
        cpu: "1"
        memory: 3Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
